# Alle hier gesetzten Werte können über `$addon->getProperty($key)` abgefragt werden

package: nv_modulepreview # Pflichtfeld
version: '1.4-beta' # Pflichtfeld
author: novinet GmbH & Co KG
supportpage: https://novinet.de

page:
    title: translate:nv_modulepreview_key
    icon: novinet-icon-logo
    perm: 'nv_modulepreview[]'
    pjax: true
pages:
    modules/nv_modulepreview:
        title: translate:nv_modulepreview
        perm: 'nv_modulepreview[]'
        pjax: false
        subpages:
            modules: { title: 'translate:nv_modulepreview_modules' }
            categories: { title: 'translate:nv_modulepreview_categories' }
            config: { title: 'translate:nv_modulepreview_config' }
            help: { title: 'translate:nv_modulepreview_help', subPath: README.md }